### ISSUE TITLE
HTTP 500 From Mock Server For V2 Consumer Tests

### ISSUE THREAD

**Issue by AshleyPoole** [bartschotten/com-pact#10]
Hi, i'm trying to generate a V2 pact file as a consumer but i'm getting an exception when making a call to the mocked server and the client is getting back HTTP 500.

Any idea what's wrong? Thanks!

Exception:
```
System.Exception : Unable to get data
   at MyApp.PactTests.ApiClient.Get() in C:\Temp\Example\MyApp.PactTests\ConsumerTests\ApiDataTests.cs:line 81
   at MyApp.PactTests.ApiTests.get_api_data() in C:\Temp\Example\MyApp.PactTests\ConsumerTests\ApiDataTests.cs:line 58
--- End of stack trace from previous location where exception was thrown ---

[Test Class Cleanup Failure (MyApp.PactTests.ApiTests)]: System.ArgumentNullException : Value cannot be null. (Parameter 'source')
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source)
   at ComPact.Models.V2.Response.SetEmptyValuesToNull() in C:\Temp\ComPact\Models\V2\Response.cs:line 25
   at ComPact.Models.V2.Interaction.SetEmptyValuesToNull() in C:\Temp\ComPact\Models\V2\Interaction.cs:line 29
   at ComPact.Models.V2.Contract.<>c.<SetEmptyValuesToNull>b__16_0(Interaction i) in C:\Temp\ComPact\Models\V2\Contract.cs:line 18
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at ComPact.Models.V2.Contract.SetEmptyValuesToNull() in C:\Temp\ComPact\Models\V2\Contract.cs:line 18
   at ComPact.Builders.PactWriter.Write(IContract pact, String pactDir) in C:\Temp\ComPact\Builders\PactWriter.cs:line 24
   at ComPact.Builders.PactWriter.Write(IContract pact) in C:\Temp\ComPact\Builders\PactWriter.cs:line 19
   at ComPact.Builders.PactBuilderBase.BuildAsync(IContract pact) in C:\Temp\ComPact\Builders\PactBuilderBase.cs:line 74
   at ComPact.Builders.V2.PactBuilder.BuildAsync() in C:\Temp\ComPact\Builders\V2\PactBuilder.cs:line 46
   at MyApp.PactTests.ApiConsumerFixture.Dispose() in C:\Temp\Example\MyApp.PactTests\ConsumerTests\ApiDataTests.cs:line 27
```

Here's an simple example i've built of what i'm trying to do:
```
using System;
using System.Net;
using System.Net.Http;
using System.Threading.Tasks;
using ComPact.Builders.V2;
using ComPact.Models;
using Newtonsoft.Json;
using Xunit;

namespace MyApp.PactTests
{
    public class ApiConsumerFixture : IDisposable
    {
        public ApiClient _apiClient;

        public PactBuilder PactBuilder { get; }

        public ApiConsumerFixture()
        {
            const string mockServerBaseUrl = "http://localhost:5000";

            PactBuilder = new PactBuilder("my-consumer", "my-api", mockServerBaseUrl);

            _apiClient = new ApiClient(new HttpClient { BaseAddress = new Uri(mockServerBaseUrl) });
        }

        public void Dispose() => PactBuilder.BuildAsync().GetAwaiter().GetResult();
    }

    public class ApiTests : IClassFixture<ApiConsumerFixture>
    {
        private readonly PactBuilder _pactBuilder;
        private readonly ApiClient _apiClient;

        public ApiTests(ApiConsumerFixture fixture)
        {
            _apiClient = fixture._apiClient;

            _pactBuilder = fixture.PactBuilder;
            _pactBuilder.ClearInteractions();
        }

        [Fact]
        public async Task get_api_data()
        {
            _pactBuilder.SetUp(Pact.Interaction.Given(
                    $"An request for data")
                .UponReceiving("A get request for data")
                .With(Pact.Request.WithMethod(Method.GET)
                    .WithPath("/data"))
                .WillRespondWith(Pact.Response
                    .WithStatus((int) HttpStatusCode.OK)
                    .WithHeader("Content-Type", "application/json; charset=utf-8")
                    .WithBody(Pact.JsonContent
                        .With(Some.Element.Named("Id").WithTheExactValue("123456"))
                        .With(Some.Element.Named("SomeInt").WithTheExactValue("98765")))));

            await _apiClient.Get();
        }
    }

    public class ApiClient
    {
        private readonly HttpClient _httpClient;

        public ApiClient(HttpClient httpClient)
        {
            _httpClient = httpClient;
        }

        public async Task<ApiResponse> Get()
        {
            var request = new HttpRequestMessage(HttpMethod.Get, "/data");
            var response = await _httpClient.SendAsync(request);

            if (!response.IsSuccessStatusCode)
            {
                throw new Exception("Unable to get data");
            }

            var responseBody = await response.Content.ReadAsStringAsync();
            return JsonConvert.DeserializeObject<ApiResponse>(responseBody);
        }
    }

    public class ApiResponse
    {
        public string Id { get; set; }

        public int SomeInt { get; set; }
    }
}
```

**Comment by bartschotten** [comment]
Ah yes, well spotted. Because there were no matching rules defined it failed when trying to set a property to null that was already null.

I just fixed it.

**Comment by AshleyPoole** [comment]
Thanks @bartschotten! I've just tried with 0.3.1 of the package though i'm still getting the same HTTP 500 error back when calling the mocked servers URL using the above example. That's then leading to the api client thrown an exception as it got back a non-expected response code that was configured.

```
           at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source)
   at ComPact.Models.V2.Response.SetEmptyValuesToNull() in C:\Temp\ComPact\Models\V2\Response.cs:line 25
   at ComPact.Models.V2.Interaction.SetEmptyValuesToNull() in C:\Temp\ComPact\Models\V2\Interaction.cs:line 29
   at ComPact.Models.V2.Contract.<>c.<SetEmptyValuesToNull>b__16_0(Interaction i) in C:\Temp\ComPact\Models\V2\Contract.cs:line 18
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at ComPact.Models.V2.Contract.SetEmptyValuesToNull() in C:\Temp\ComPact\Models\V2\Contract.cs:line 18
   at ComPact.Builders.PactWriter.Write(IContract pact, String pactDir) in C:\Temp\ComPact\Builders\PactWriter.cs:line 24
   at ComPact.Builders.PactWriter.Write(IContract pact) in C:\Temp\ComPact\Builders\PactWriter.cs:line 19
   at ComPact.Builders.PactBuilderBase.<BuildAsync>d__13.MoveNext() in C:\Temp\ComPact\Builders\PactBuilderBase.cs:line 74
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at ComPact.Builders.V2.PactBuilder.<BuildAsync>d__4.MoveNext() in C:\Temp\ComPact\Builders\V2\PactBuilder.cs:line 46
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at MyApp.PactTests.ApiConsumerFixture.Dispose() in C:\temp\example\MyApp.PactTests\ConsumerTests\ApiDataTests.cs:line 27
   at Xunit.Sdk.ExceptionAggregator.Run(Action code) in C:\Dev\xunit\xunit\src\xunit.core\Sdk\ExceptionAggregator.cs:line 73

``` 

If it helps, i'm trying to use this in a netcoreapp3.1 test project with xunit 2.4.0.

**Comment by bartschotten** [comment]
Are you sure you updated the package? I tried to reproduce it with your exact code, and I get the error you described with 0.3.0, but with 0.3.1 it throws the exception you define in your ApiClient class "Unable to get data".

**Comment by AshleyPoole** [comment]
Yes, confirmed, using 0.3.1. I even tried removing the package and adding the project directly from source code and still got the issue. Here's a full copy of the CSPROJ, i'm not sure any of those other packages would create an issue, unless maybe it's an issue with .NET 3.1 and the test host'?

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>

    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ComPact" Version="0.3.1" />
    <PackageReference Include="Microsoft.AspNetCore" Version="2.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.TestHost" Version="3.1.4" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="16.6.1" />
    <PackageReference Include="xunit" Version="2.4.0" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.4.0" />
    <PackageReference Include="coverlet.collector" Version="1.0.1" />
    <PackageReference Include="Moq" Version="4.13.1" />
  </ItemGroup>

</Project>

```

**Comment by AshleyPoole** [comment]
It appears its the "ClearInteractions" call in the test fixture that it's not happy about. If i removed that call from the constructor for the test class, the test then passes. With Pact we had to clear interactions after every test class to ensure there we no previous interactions carried over.

**Comment by AshleyPoole** [comment]
Also seeming some weird behaviour where on the first test run, it passes, but an sequential runs it fails. I wonder if the mock isn't being shutdown for some reason?

**Comment by bartschotten** [comment]
I did find a bug in ClearInteractions. Thanks for that! It isn't really necessary to call it under normal circumstances though.

The mock should definitely be shut down when calling BuildAsync. If you try to call the mock after that you should be able to see it fail.

**Comment by bartschotten** [comment]
Are you still seeing the problem with the latest version?

**Comment by AshleyPoole** [comment]
Latest version has resolved the issue I was getting with with consume setup, thanks! I'll try a provider now against those tests and see how I get on...
