### ISSUE TITLE
ArgumentNullException when matchingRules are empty

### ISSUE THREAD

**Issue by Kampfmoehre** [bartschotten/com-pact#21]
Hi, I just discovered your library and wanted to give it a try since the official one does not support messages.

We have some NodeJS backends that consume messages via AMQP and wanted to create Pact tests for it. So we use the official [pact-js](https://github.com/pact-foundation/pact-js) package. This works for other backends that are also NodeJS but unfortunately I can not get it to work in our Net 5 backend with your library.

`Pact-js` creates pacts where the `matchingRules` property is just an empty object. This however seems to break the Verifier with an ArgumentNullException. I have debugged a bit and it seems this is caused by this line https://github.com/bartschotten/com-pact/blob/a6a9738eddcf095c3e1c9bcceb8e299f47a0fa93/ComPact/Models/MatchingRuleCollection.cs#L40
Is there anything that I can do to make this work with a consumer using the `pact-js` module and a provider using this libary?
I also tried to use the `10.0.0-beta.29` and set the `specVersion` to 3 but it still comes with empty `matchingRules` object.

**Comment by bartschotten** [comment]
Good find. Should be fixed in 0.4.3. Can you confirm?

**Comment by Kampfmoehre** [comment]
Hi, unfortunately I'm in holiday now but I will check somewhere after the 15. february. I will close this issue and reopen if I find that the problem still exists.
Thank you for the quick fix.

**Comment by Kampfmoehre** [comment]
Just for info, I can confirm it does no longer throw an exception. Thank you for the quick fix.
